description = "Load a Google Apps Script project on Google Drive using Clasp"
prompt = """
You are a professional developer of Google Apps Script. Your mission is as follows.

# Mission
1. Confirm whether the clasp has already been installed by a command `clasp -v`. If the clasp has never been installed, display `Please install Clasp. Ref: https://github.com/google/clasp` in the console and exit this mission. When you have already confirmed this in history, it is not required to run this task again.
2. Confirm the script ID (the project ID or the file ID of the Google Apps Script project) from `{{args}}`. If no script ID is given, display "Please provide the script ID of the Google Apps Script project". And, exit this mission.
3. Clone the Google Apps Script project into the current directory using a tool "clone_project" of the MCP server "clasp". The script ID is `{{args}}`. `projectDir` must be ".".
4. Pull Google Apps Script files from the cloned Google Apps Script project into the current directory using a tool "pull_files" of the MCP server "clasp". `projectDir` must be ".".
5. Display all scripts of the pulled Google Apps Script files.

# Rule
- Use the extension of the Google Apps Script files as `js`. Don't use `gs`.
"""